import type { Country } from '@/lib/geolocation';
import { resolveQuizCountry } from '@/lib/geolocation';
import { TRAMPOLINES as COMPARE_ROWS } from '@/data/trampolines';

export type SpringType = 'springless' | 'traditional';
export type Shape = 'round' | 'oval' | 'square' | 'rectangle';
export type PriorityId = 'bounce' | 'durability' | 'value' | 'warranty';

export interface MatchReasonBank {
  springless?: string;
  traditional?: string;
  shapeRound?: string;
  shapeRectangle?: string;
  safetyEssential?: string;
  safetyNiceToHave?: string;
  meetsStandards?: string;
  smallYard?: string;
  mediumYard?: string;
  largeYard?: string;
  longNarrowYard?: string;
  budget_under_500?: string;
  budget_500_1000?: string;
  budget_1000_1500?: string;
  budget_1500_2500?: string;
  budget_2500_plus?: string;
  bounce?: string;
  durability?: string;
  valueForMoney?: string;
  warranty?: string;
}

export interface Trampoline {
  id: string;
  displayName: string;
  brand: string;
  springType: SpringType;
  shape: Shape;
  advancedSafety: boolean;
  meetsAUStandards: boolean;
  meetsUSStandards: boolean;
  availableIn: Array<'AU' | 'US'>;
  priceFrom: number;
  sizes: number[]; // ft (approximate for metric models); used for multi-size selection
  displaySize: string; // shown on results card e.g. "12ft" or "2.4m × 3.4m oval"
  image: string; // path under /images/
  slug: string;
  isVuly: boolean;
  fitsYard: { small: boolean; medium: boolean; large: boolean; longNarrow: boolean };
  bestFor: string;
  metricScores: Record<PriorityId, number>;
  matchReasons: MatchReasonBank;
}

const baseTrampolines: Trampoline[] = [

  // ─── Vuly ──────────────────────────────────────────────────────────────────

  {
    id: 'vuly-thunder-2-pro',
    displayName: 'Thunder 2 Pro',
    brand: 'Vuly',
    springType: 'springless',
    shape: 'round',
    advancedSafety: true,
    meetsAUStandards: true,
    meetsUSStandards: true,
    availableIn: ['AU', 'US'],
    priceFrom: 2099,
    sizes: [10, 12, 14],
    displaySize: '10ft, 12ft or 14ft',
    image: '/images/vuly/thunder-2-pro.webp',
    slug: 'vuly-thunder-2-pro',
    isVuly: true,
    fitsYard: { small: true, medium: true, large: true, longNarrow: false },
    bestFor: 'Families wanting the safest premium Vuly springless model.',
    metricScores: { bounce: 8, durability: 10, value: 4, warranty: 9 },
    matchReasons: {
      springless: 'Springless leaf-spring system — no exposed metal coil springs anywhere on the frame',
      safetyEssential: 'Maximum safety — curved poles angle away from jumpers, springs sit outside the net, frame positioned away from the jump zone',
      safetyNiceToHave: 'Strong safety features including curved poles and an external spring system',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      smallYard: 'Available in 10ft — fits your smaller backyard (allow 1m clearance on all sides)',
      mediumYard: 'Available in 12ft — the ideal size for a medium-sized backyard',
      largeYard: 'Available up to 14ft — makes the most of your large backyard',
      budget_1500_2500: 'Fits comfortably within the $1,500–$2,500 premium range',
      budget_2500_plus: 'A top-tier investment piece for long-term family use',
      durability: '10-year frame warranty — built for years of heavy family use',
      warranty: 'Backed by Vuly\'s 10-year frame warranty',
    },
  },

  {
    id: 'vuly-thunder-2',
    displayName: 'Thunder 2',
    brand: 'Vuly',
    springType: 'springless',
    shape: 'round',
    advancedSafety: true,
    meetsAUStandards: true,
    meetsUSStandards: true,
    availableIn: ['AU', 'US'],
    priceFrom: 1399,
    sizes: [10, 12, 14, 16],
    displaySize: '10ft, 12ft, 14ft or 16ft',
    image: '/images/vuly/thunder-2.webp',
    slug: 'vuly-thunder-2',
    isVuly: true,
    fitsYard: { small: true, medium: true, large: true, longNarrow: false },
    bestFor: 'Families wanting a springless Vuly at a lower entry price than the Pro.',
    metricScores: { bounce: 8, durability: 8, value: 6, warranty: 9 },
    matchReasons: {
      springless: 'Springless leaf-spring system — no exposed metal coil springs',
      safetyEssential: 'Very high safety — curved poles and springless design remove the most common injury points',
      safetyNiceToHave: 'Strong safety features — curved poles and springless design',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      smallYard: 'Available in 10ft — fits smaller backyards',
      mediumYard: 'Available in 12ft — ideal for a medium-sized backyard',
      largeYard: 'Available up to 14ft for your large backyard',
      budget_1000_1500: 'Strong springless option in the $1,000–$1,500 range',
      budget_1500_2500: 'Fits your $1,500–$2,500 budget with strong safety credentials',
      durability: 'High-quality components built for long-term family use',
      warranty: 'Strong warranty coverage from Vuly',
    },
  },

  {
    id: 'vuly-ultra-2-pro',
    displayName: 'Ultra 2 Pro',
    brand: 'Vuly',
    springType: 'traditional',
    shape: 'round',
    advancedSafety: true,
    meetsAUStandards: true,
    meetsUSStandards: true,
    availableIn: ['AU', 'US'],
    priceFrom: 1199,
    sizes: [10, 12, 14],
    displaySize: '10ft, 12ft or 14ft',
    image: '/images/vuly/ultra-2-pro.webp',
    slug: 'vuly-ultra-2-pro',
    isVuly: true,
    fitsYard: { small: true, medium: true, large: true, longNarrow: false },
    bestFor: 'Buyers who want a premium Vuly spring trampoline with excellent bounce.',
    metricScores: { bounce: 8, durability: 8, value: 7, warranty: 8 },
    matchReasons: {
      traditional: 'Traditional spring system tuned for excellent bounce quality',
      safetyEssential: 'High safety — curved safety poles and premium enclosure design',
      safetyNiceToHave: 'Good safety features including curved poles',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      smallYard: 'Available in 10ft — fits your smaller backyard',
      mediumYard: 'Available in 12ft — ideal for a medium-sized backyard',
      largeYard: 'Available up to 14ft for your large backyard',
      budget_1000_1500: 'Premium spring trampoline in the $1,000–$1,500 range',
      budget_1500_2500: 'Fits your budget and delivers premium performance',
      valueForMoney: 'Strong value — premium features at a mid-range price',
      warranty: 'Good warranty coverage from Vuly',
    },
  },

  {
    id: 'vuly-ultra-2',
    displayName: 'Ultra 2',
    brand: 'Vuly',
    springType: 'traditional',
    shape: 'round',
    advancedSafety: true,
    meetsAUStandards: true,
    meetsUSStandards: true,
    availableIn: ['AU', 'US'],
    priceFrom: 799,
    sizes: [8, 10, 12, 14],
    displaySize: '8ft, 10ft, 12ft or 14ft',
    image: '/images/vuly/ultra-2.webp',
    slug: 'vuly-ultra-2',
    isVuly: true,
    fitsYard: { small: true, medium: true, large: true, longNarrow: false },
    bestFor: 'Families after a mid-range Vuly spring model with broad appeal.',
    metricScores: { bounce: 8, durability: 7, value: 8, warranty: 8 },
    matchReasons: {
      traditional: 'Traditional spring system for a dependable, responsive bounce',
      safetyNiceToHave: 'Good safety design — Vuly build quality with solid enclosure',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      smallYard: 'Available in 10ft — fits smaller backyards',
      mediumYard: 'Available in 12ft — ideal for a medium-sized backyard',
      largeYard: 'Available up to 14ft for your large backyard',
      budget_500_1000: 'Vuly quality in the $500–$1,000 range',
      budget_1000_1500: 'Fits your budget with Vuly\'s quality backing',
      valueForMoney: 'Strong value — Vuly quality at a mid-range price',
      warranty: 'Good warranty coverage from Vuly',
    },
  },

  {
    id: 'vuly-flare',
    displayName: 'Flare',
    brand: 'Vuly',
    springType: 'traditional',
    shape: 'round',
    advancedSafety: false,
    meetsAUStandards: true,
    meetsUSStandards: true,
    availableIn: ['AU', 'US'],
    priceFrom: 499,
    sizes: [10, 12, 14],
    displaySize: '10ft, 12ft or 14ft',
    image: '/images/vuly/flare.webp',
    slug: 'vuly-flare',
    isVuly: true,
    fitsYard: { small: true, medium: true, large: true, longNarrow: false },
    bestFor: 'Budget-conscious families who want Vuly quality at the entry-level price point.',
    metricScores: { bounce: 8, durability: 7, value: 9, warranty: 7 },
    matchReasons: {
      traditional: 'Traditional spring system — good bounce, familiar feel',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      smallYard: 'Available in 10ft — fits smaller backyards',
      mediumYard: 'Available in 12ft — ideal for a medium-sized backyard',
      largeYard: 'Available up to 14ft for your large backyard',
      budget_under_500: 'Starting at $499 — fits your under-$500 budget',
      budget_500_1000: 'Vuly quality in the $500–$1,000 range',
      valueForMoney: 'Entry-level price point with Vuly\'s brand backing',
      warranty: 'Covered by Vuly\'s warranty program',
    },
  },

  // ─── Springfree ────────────────────────────────────────────────────────────

  {
    id: 'springfree-mini-round',
    displayName: 'Mini Round',
    brand: 'Springfree',
    springType: 'springless',
    shape: 'round',
    advancedSafety: true,
    meetsAUStandards: true,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 899,
    sizes: [6],
    displaySize: '6ft (1.8m)',
    image: '/images/springfree/mini-round.webp',
    slug: 'springfree-mini-round',
    isVuly: false,
    fitsYard: { small: true, medium: false, large: false, longNarrow: false },
    bestFor: 'Young kids in tight urban backyards who need maximum safety in a small footprint.',
    metricScores: { bounce: 8, durability: 10, value: 6, warranty: 10 },
    matchReasons: {
      springless: 'Composite rod system — no exposed springs, no pinch points anywhere',
      safetyEssential: 'Maximum safety design — composite rods, SoftEdge mat, hidden frame with no hard edges',
      safetyNiceToHave: 'Excellent safety — composite rods replace metal springs entirely',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      smallYard: '6ft (1.8m) — perfect for tight urban backyards and young children',
      durability: '10-year warranty on all components — built to last',
      warranty: 'Industry-leading 10-year warranty on all components',
    },
  },

  {
    id: 'springfree-compact-round',
    displayName: 'Compact Round',
    brand: 'Springfree',
    springType: 'springless',
    shape: 'round',
    advancedSafety: true,
    meetsAUStandards: true,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 1199,
    sizes: [8],
    displaySize: '8ft (2.5m)',
    image: '/images/springfree/compact-round.webp',
    slug: 'springfree-compact-round',
    isVuly: false,
    fitsYard: { small: true, medium: false, large: false, longNarrow: false },
    bestFor: 'Small urban yards that need maximum safety in a compact footprint.',
    metricScores: { bounce: 8, durability: 10, value: 6, warranty: 10 },
    matchReasons: {
      springless: 'Composite rod system — no exposed springs, no pinch points',
      safetyEssential: 'Maximum safety — composite rods, SoftEdge mat, hidden frame',
      safetyNiceToHave: 'Excellent safety — composite rods replace metal springs entirely',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      smallYard: '8ft (2.5m) — fits small backyards while maximising the jump zone',
      budget_1000_1500: 'Maximum safety in the $1,000–$1,500 range',
      durability: '10-year warranty on all components',
      warranty: 'Industry-leading 10-year warranty on all components',
    },
  },

  {
    id: 'springfree-medium-round',
    displayName: 'Medium Round',
    brand: 'Springfree',
    springType: 'springless',
    shape: 'round',
    advancedSafety: true,
    meetsAUStandards: true,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 2099,
    sizes: [10],
    displaySize: '10ft (3m)',
    image: '/images/springfree/medium-round.jpg',
    slug: 'springfree-medium-round',
    isVuly: false,
    fitsYard: { small: true, medium: true, large: false, longNarrow: false },
    bestFor: 'Families wanting a mid-size Springfree round for mixed-age use.',
    metricScores: { bounce: 8, durability: 10, value: 5, warranty: 10 },
    matchReasons: {
      springless: 'Composite rod system — no exposed springs',
      safetyEssential: 'Maximum safety — composite rods, SoftEdge mat, hidden frame',
      safetyNiceToHave: 'Excellent safety — composite rods replace metal springs entirely',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      smallYard: '10ft (3m) — a good springless fit for smaller to medium yards',
      mediumYard: '10ft (3m) — great fit for medium-sized backyards',
      budget_1500_2500: 'Maximum safety in the $1,500–$2,500 range',
      budget_2500_plus: 'Premium investment for maximum safety',
      durability: '10-year warranty on all components',
      warranty: 'Industry-leading 10-year warranty on all components',
    },
  },

  {
    id: 'springfree-jumbo-round',
    displayName: 'Jumbo Round',
    brand: 'Springfree',
    springType: 'springless',
    shape: 'round',
    advancedSafety: true,
    meetsAUStandards: true,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 3199,
    sizes: [13],
    displaySize: '13ft (4m)',
    image: '/images/springfree/jumbo-round.webp',
    slug: 'springfree-jumbo-round',
    isVuly: false,
    fitsYard: { small: false, medium: false, large: true, longNarrow: false },
    bestFor: 'Large families wanting maximum Springfree jumping space.',
    metricScores: { bounce: 8, durability: 10, value: 4, warranty: 10 },
    matchReasons: {
      springless: 'Composite rod system — no exposed springs',
      safetyEssential: 'Maximum safety design at jumbo scale — composite rods and SoftEdge mat',
      safetyNiceToHave: 'Excellent safety from Springfree\'s composite rod system',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      mediumYard: '13ft (4m) — best suited to medium-large yards',
      largeYard: '13ft (4m) — ideal for large backyards and whole-family use',
      budget_2500_plus: 'Premium whole-family springless trampoline',
      durability: '10-year warranty on all components',
      warranty: 'Industry-leading 10-year warranty on all components',
    },
  },

  {
    id: 'springfree-compact-oval',
    displayName: 'Compact Oval',
    brand: 'Springfree',
    springType: 'springless',
    shape: 'oval',
    advancedSafety: true,
    meetsAUStandards: true,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 1599,
    sizes: [7],
    displaySize: '1.9m × 2.7m',
    image: '/images/springfree/compact-oval.webp',
    slug: 'springfree-compact-oval',
    isVuly: false,
    fitsYard: { small: true, medium: false, large: false, longNarrow: true },
    bestFor: 'Long narrow yards that need a safe springless option in a compact oval footprint.',
    metricScores: { bounce: 8, durability: 10, value: 6, warranty: 10 },
    matchReasons: {
      springless: 'Composite rod system — no exposed springs, no pinch points',
      safetyEssential: 'Maximum safety — composite rods, SoftEdge mat, hidden frame',
      safetyNiceToHave: 'Excellent safety from Springfree\'s composite rod system',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      smallYard: '1.9m × 2.7m — compact enough for smaller yards',
      longNarrowYard: 'Oval shape (1.9m × 2.7m) — designed specifically for long, narrow backyard layouts',
      budget_1500_2500: 'Maximum safety in your budget range',
      durability: '10-year warranty on all components',
      warranty: 'Industry-leading 10-year warranty on all components',
    },
  },

  {
    id: 'springfree-medium-oval',
    displayName: 'Medium Oval',
    brand: 'Springfree',
    springType: 'springless',
    shape: 'oval',
    advancedSafety: true,
    meetsAUStandards: true,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 1999,
    sizes: [9],
    displaySize: '2.4m × 3.4m',
    image: '/images/springfree/medium-oval.webp',
    slug: 'springfree-medium-oval',
    isVuly: false,
    fitsYard: { small: false, medium: true, large: false, longNarrow: true },
    bestFor: 'Medium-sized yards with a long narrow layout.',
    metricScores: { bounce: 8, durability: 10, value: 5, warranty: 10 },
    matchReasons: {
      springless: 'Composite rod system — no exposed springs',
      safetyEssential: 'Maximum safety — composite rods, SoftEdge mat, hidden frame',
      safetyNiceToHave: 'Excellent safety from Springfree\'s composite rod system',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      mediumYard: '2.4m × 3.4m — great fit for medium-sized backyards',
      longNarrowYard: 'Oval shape (2.4m × 3.4m) — perfect for long, narrow yards',
      budget_1500_2500: 'Maximum safety in the $1,500–$2,500 range',
      budget_2500_plus: 'Premium springless oval',
      durability: '10-year warranty on all components',
      warranty: 'Industry-leading 10-year warranty on all components',
    },
  },

  {
    id: 'springfree-large-oval',
    displayName: 'Large Oval',
    brand: 'Springfree',
    springType: 'springless',
    shape: 'oval',
    advancedSafety: true,
    meetsAUStandards: true,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 2299,
    sizes: [11],
    displaySize: '2.4m × 4m',
    image: '/images/springfree/large-oval.webp',
    slug: 'springfree-large-oval',
    isVuly: false,
    fitsYard: { small: false, medium: true, large: true, longNarrow: true },
    bestFor: 'Larger yards with a long narrow layout needing extra length.',
    metricScores: { bounce: 8, durability: 10, value: 5, warranty: 10 },
    matchReasons: {
      springless: 'Composite rod system — no exposed springs',
      safetyEssential: 'Maximum safety — composite rods, SoftEdge mat, hidden frame',
      safetyNiceToHave: 'Excellent safety from Springfree\'s composite rod system',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      mediumYard: '2.4m × 4m — good fit for medium to large yards',
      largeYard: '2.4m × 4m — extra-long jumping surface for larger backyards',
      longNarrowYard: 'Oval shape (2.4m × 4m) — designed for long, narrow backyard layouts',
      budget_1500_2500: 'Top-tier springless safety in your budget',
      budget_2500_plus: 'Premium oval for serious family use',
      durability: '10-year warranty on all components',
      warranty: 'Industry-leading 10-year warranty on all components',
    },
  },

  {
    id: 'springfree-jumbo-oval',
    displayName: 'Jumbo Oval',
    brand: 'Springfree',
    springType: 'springless',
    shape: 'oval',
    advancedSafety: true,
    meetsAUStandards: true,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 4399,
    sizes: [15],
    displaySize: '3.8m × 5.7m',
    image: '/images/springfree/jumbo-oval.webp',
    slug: 'springfree-jumbo-oval',
    isVuly: false,
    fitsYard: { small: false, medium: false, large: true, longNarrow: true },
    bestFor: 'Huge yards and athletes who want the largest oval Springfree makes.',
    metricScores: { bounce: 8, durability: 10, value: 3, warranty: 10 },
    matchReasons: {
      springless: 'Composite rod system — no exposed springs',
      safetyEssential: 'Maximum safety design at jumbo scale',
      safetyNiceToHave: 'Excellent safety from Springfree\'s composite rod system',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      largeYard: '3.8m × 5.7m — designed for large open yards and serious family use',
      longNarrowYard: 'Jumbo oval (3.8m × 5.7m) — built for generous long, narrow yard spaces',
      budget_2500_plus: 'Premium jumbo investment for the whole family',
      durability: '10-year warranty on all components',
      warranty: 'Industry-leading 10-year warranty on all components',
    },
  },

  {
    id: 'springfree-medium-square',
    displayName: 'Medium Square',
    brand: 'Springfree',
    springType: 'springless',
    shape: 'square',
    advancedSafety: true,
    meetsAUStandards: true,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 2099,
    sizes: [9],
    displaySize: '2.7m × 2.7m',
    image: '/images/springfree/medium-square.jpg',
    slug: 'springfree-medium-square',
    isVuly: false,
    fitsYard: { small: true, medium: true, large: false, longNarrow: false },
    bestFor: 'Medium yards wanting maximum corner-to-corner jumping area in a square shape.',
    metricScores: { bounce: 8, durability: 10, value: 5, warranty: 10 },
    matchReasons: {
      springless: 'Composite rod system — no exposed springs',
      safetyEssential: 'Maximum safety — composite rods, SoftEdge mat, hidden frame',
      safetyNiceToHave: 'Excellent safety from Springfree\'s composite rod system',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      shapeRectangle: 'Square 2.7m × 2.7m mat — straight-edged jump area in a springless design',
      smallYard: '2.7m × 2.7m square — fits small to medium backyards with maximum usable jump area',
      mediumYard: '2.7m × 2.7m square — maximises usable jump area for medium backyards',
      budget_1500_2500: 'Maximum safety in your budget range',
      durability: '10-year warranty on all components',
      warranty: 'Industry-leading 10-year warranty on all components',
    },
  },

  {
    id: 'springfree-large-square',
    displayName: 'Large Square',
    brand: 'Springfree',
    springType: 'springless',
    shape: 'square',
    advancedSafety: true,
    meetsAUStandards: true,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 2699,
    sizes: [11],
    displaySize: '3.4m × 3.4m',
    image: '/images/springfree/large-square.webp',
    slug: 'springfree-large-square',
    isVuly: false,
    fitsYard: { small: false, medium: true, large: true, longNarrow: false },
    bestFor: 'Larger backyards wanting the maximum Springfree square jump area.',
    metricScores: { bounce: 8, durability: 10, value: 4, warranty: 10 },
    matchReasons: {
      springless: 'Composite rod system — no exposed springs',
      safetyEssential: 'Maximum safety — composite rods, SoftEdge mat, hidden frame',
      safetyNiceToHave: 'Excellent safety from Springfree\'s composite rod system',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      shapeRectangle: 'Square 3.4m × 3.4m mat — big straight-edged jump area in a springless design',
      mediumYard: '3.4m × 3.4m square — maximises jump area in a medium to large yard',
      largeYard: '3.4m × 3.4m — excellent for larger backyards',
      budget_2500_plus: 'Premium large square — worth the investment',
      durability: '10-year warranty on all components',
      warranty: 'Industry-leading 10-year warranty on all components',
    },
  },

  {
    id: 'springfree-jumbo-square',
    displayName: 'Jumbo Square',
    brand: 'Springfree',
    springType: 'springless',
    shape: 'square',
    advancedSafety: true,
    meetsAUStandards: true,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 3499,
    sizes: [13],
    displaySize: '4m × 4m',
    image: '/images/springfree/jumbo-square.webp',
    slug: 'springfree-jumbo-square',
    isVuly: false,
    fitsYard: { small: false, medium: false, large: true, longNarrow: false },
    bestFor: 'Large yards wanting the biggest possible square Springfree.',
    metricScores: { bounce: 8, durability: 10, value: 3, warranty: 10 },
    matchReasons: {
      springless: 'Composite rod system — no exposed springs',
      safetyEssential: 'Maximum safety at jumbo scale — composite rods and SoftEdge mat',
      safetyNiceToHave: 'Excellent safety from Springfree\'s composite rod system',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      shapeRectangle: 'Square 4m × 4m mat — the biggest straight-edged springless jump area available',
      largeYard: '4m × 4m — the biggest Springfree square, built for large backyards',
      budget_2500_plus: 'Jumbo premium square for serious families',
      durability: '10-year warranty on all components',
      warranty: 'Industry-leading 10-year warranty on all components',
    },
  },

  // ─── Jumpflex ──────────────────────────────────────────────────────────────

  {
    id: 'jumpflex-flex-10ft',
    displayName: 'Flex 10ft',
    brand: 'Jumpflex',
    springType: 'traditional',
    shape: 'round',
    advancedSafety: false,
    meetsAUStandards: false,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 599,
    sizes: [10],
    displaySize: '10ft',
    image: '/images/jumpflex/flex.png',
    slug: 'jumpflex-flex-10ft',
    isVuly: false,
    fitsYard: { small: true, medium: false, large: false, longNarrow: false },
    bestFor: 'Budget-conscious families with smaller yards who want a certified spring model.',
    metricScores: { bounce: 8, durability: 6, value: 9, warranty: 6 },
    matchReasons: {
      traditional: 'Traditional spring system — straightforward bounce',
      smallYard: '10ft size — fits smaller backyards well',
      budget_500_1000: 'Budget-friendly option at $599',
      budget_under_500: 'Just above $500 — competitive budget spring trampoline',
      valueForMoney: 'Good value for a basic family trampoline',
    },
  },

  {
    id: 'jumpflex-flex-12ft',
    displayName: 'Flex 12ft',
    brand: 'Jumpflex',
    springType: 'traditional',
    shape: 'round',
    advancedSafety: false,
    meetsAUStandards: false,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 799,
    sizes: [12],
    displaySize: '12ft',
    image: '/images/jumpflex/flex.png',
    slug: 'jumpflex-flex-12ft',
    isVuly: false,
    fitsYard: { small: false, medium: true, large: false, longNarrow: false },
    bestFor: 'Budget families with medium yards who want a dependable spring model.',
    metricScores: { bounce: 8, durability: 6, value: 9, warranty: 6 },
    matchReasons: {
      traditional: 'Traditional spring system — dependable bounce',
      mediumYard: '12ft — ideal size for a medium-sized backyard',
      budget_500_1000: 'Good value at $799 for a 12ft model',
      budget_1000_1500: 'Well priced at the lower end of the $1,000–$1,500 range',
      valueForMoney: 'Good value for a standard family trampoline',
    },
  },

  {
    id: 'jumpflex-hero-10ft',
    displayName: 'Hero 10ft',
    brand: 'Jumpflex',
    springType: 'traditional',
    shape: 'round',
    advancedSafety: true,
    meetsAUStandards: false,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 999,
    sizes: [10],
    displaySize: '10ft',
    image: '/images/jumpflex/hero.png',
    slug: 'jumpflex-hero-10ft',
    isVuly: false,
    fitsYard: { small: true, medium: false, large: false, longNarrow: false },
    bestFor: 'Families in smaller yards wanting high-safety spring performance without the springless price.',
    metricScores: { bounce: 8, durability: 8, value: 8, warranty: 8 },
    matchReasons: {
      traditional: 'Traditional spring system with a high-performance curved-pole safety design',
      safetyEssential: 'High safety — curved poles, DualRing reinforced frame, and TightWeave enclosure net',
      safetyNiceToHave: 'Strong safety features — curved poles and reinforced DualRing frame',
      smallYard: '10ft — good for smaller backyards without sacrificing quality',
      budget_500_1000: 'Premium safety in the $500–$1,000 range',
      budget_1000_1500: 'Strong value for the safety specification included',
      durability: 'Reinforced DualRing frame with 10-year warranty',
      warranty: '10-year frame warranty from Jumpflex',
      valueForMoney: 'High-safety spring trampoline at a competitive price',
    },
  },

  {
    id: 'jumpflex-hero-12ft',
    displayName: 'Hero 12ft',
    brand: 'Jumpflex',
    springType: 'traditional',
    shape: 'round',
    advancedSafety: true,
    meetsAUStandards: false,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 1299,
    sizes: [12],
    displaySize: '12ft',
    image: '/images/jumpflex/hero.png',
    slug: 'jumpflex-hero-12ft',
    isVuly: false,
    fitsYard: { small: false, medium: true, large: false, longNarrow: false },
    bestFor: 'Medium yard families wanting high-safety spring performance.',
    metricScores: { bounce: 8, durability: 8, value: 8, warranty: 8 },
    matchReasons: {
      traditional: 'Traditional spring system with high-performance curved-pole safety design',
      safetyEssential: 'High safety — curved poles, DualRing reinforced frame, TightWeave enclosure net',
      safetyNiceToHave: 'Strong safety features — curved poles and reinforced DualRing frame',
      mediumYard: '12ft — ideal for a medium-sized backyard',
      budget_1000_1500: 'High-safety spring trampoline in the $1,000–$1,500 range',
      budget_1500_2500: 'Good value relative to premium springless options',
      durability: 'Reinforced DualRing frame with 10-year warranty',
      warranty: '10-year frame warranty from Jumpflex',
      valueForMoney: 'High-safety spring trampoline at a competitive price',
    },
  },

  {
    id: 'jumpflex-hero-14ft',
    displayName: 'Hero 14ft',
    brand: 'Jumpflex',
    springType: 'traditional',
    shape: 'round',
    advancedSafety: true,
    meetsAUStandards: false,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 1599,
    sizes: [14],
    displaySize: '14ft',
    image: '/images/jumpflex/hero.png',
    slug: 'jumpflex-hero-14ft',
    isVuly: false,
    fitsYard: { small: false, medium: false, large: true, longNarrow: false },
    bestFor: 'Large yard families wanting high-safety spring performance in a 14ft model.',
    metricScores: { bounce: 8, durability: 8, value: 7, warranty: 8 },
    matchReasons: {
      traditional: 'Traditional spring system with high-performance curved-pole design',
      safetyEssential: 'High safety — curved poles, DualRing frame, TightWeave enclosure net',
      safetyNiceToHave: 'Strong safety features — curved poles and reinforced DualRing frame',
      largeYard: '14ft — makes the most of your large backyard',
      budget_1500_2500: 'Large high-safety spring trampoline in your budget range',
      durability: 'Reinforced DualRing frame with 10-year warranty',
      warranty: '10-year frame warranty from Jumpflex',
    },
  },

  {
    id: 'jumpflex-hero-15ft',
    displayName: 'Hero 15ft',
    brand: 'Jumpflex',
    springType: 'traditional',
    shape: 'round',
    advancedSafety: true,
    meetsAUStandards: false,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 1299,
    sizes: [15],
    displaySize: '15ft',
    image: '/images/jumpflex/hero.png',
    slug: 'jumpflex-hero-15ft',
    isVuly: false,
    fitsYard: { small: false, medium: false, large: true, longNarrow: false },
    bestFor: 'Large-yard families who want the biggest round Jumpflex Hero option.',
    metricScores: { bounce: 8, durability: 8, value: 7, warranty: 8 },
    matchReasons: {
      traditional: 'Traditional spring system with Jumpflex\'s curved-pole safety layout',
      safetyEssential: 'High safety — curved poles, DualRing frame, and TightWeave net',
      safetyNiceToHave: 'Strong safety features for a spring trampoline',
      largeYard: '15ft — fills a large backyard with more jumping space',
      budget_1000_1500: 'Large premium spring option in the $1,000–$1,500 range',
      budget_1500_2500: 'Competitive large-format trampoline versus pricier premium models',
      durability: 'Reinforced frame backed by a 10-year warranty',
      warranty: '10-year frame warranty from Jumpflex',
    },
  },

  {
    id: 'jumpflex-mega-14ft',
    displayName: 'MEGA 14ft',
    brand: 'Jumpflex',
    springType: 'traditional',
    shape: 'square',
    advancedSafety: true,
    meetsAUStandards: false,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 2099,
    sizes: [14],
    displaySize: '14ft square',
    image: '/images/jumpflex/mega-14ft.jpg',
    slug: 'jumpflex-mega-14ft',
    isVuly: false,
    fitsYard: { small: false, medium: false, large: true, longNarrow: false },
    bestFor: 'Families who want a premium square trampoline with a big, gymnast-style jump area.',
    metricScores: { bounce: 8, durability: 9, value: 6, warranty: 8 },
    matchReasons: {
      traditional: 'Traditional piano-wire spring system for powerful rebound',
      shapeRectangle: 'Square 14ft mat — the straight-edged jump area you asked for, with more usable corners than a round',
      safetyEssential: 'Premium safety layout with Jumpflex enclosure and heavy-duty frame',
      safetyNiceToHave: 'Premium frame and enclosure package for larger users',
      largeYard: '14ft square format — needs a large open yard but maximises usable jumping space',
      budget_1500_2500: 'Premium square trampoline within your budget range',
      bounce: 'Square shape and premium spring setup deliver a strong, controlled bounce',
      durability: 'Heavy-duty frame and higher user rating suit demanding family use',
      warranty: 'Premium Jumpflex frame warranty coverage',
    },
  },

  {
    id: 'jumpflex-mega-17ft',
    displayName: 'MEGA 17ft',
    brand: 'Jumpflex',
    springType: 'traditional',
    shape: 'rectangle',
    advancedSafety: true,
    meetsAUStandards: false,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 2399,
    sizes: [17],
    displaySize: '17ft rectangle',
    image: '/images/jumpflex/mega-17ft.jpg',
    slug: 'jumpflex-mega-17ft',
    isVuly: false,
    fitsYard: { small: false, medium: false, large: true, longNarrow: true },
    bestFor: 'Long, wide backyards wanting a premium rectangle trampoline.',
    metricScores: { bounce: 8, durability: 9, value: 6, warranty: 8 },
    matchReasons: {
      traditional: 'Premium spring setup tuned for a bigger rectangle jump area',
      shapeRectangle: 'True 17ft rectangle — the long, straight jump lane you asked for',
      safetyEssential: 'Premium enclosure and heavy-duty frame for larger users',
      safetyNiceToHave: 'Strong safety design in a competition-style rectangle layout',
      largeYard: '17ft rectangle — suits very large backyards',
      longNarrowYard: 'Rectangle format makes better use of long, wide yard layouts than a giant round model',
      budget_1500_2500: 'Premium rectangle trampoline inside your target range',
      bounce: 'Rectangle geometry gives a more performance-oriented bounce feel',
      durability: 'Heavy-duty frame built for high loads and frequent use',
    },
  },

  {
    id: 'jumpflex-mega-19ft',
    displayName: 'MEGA 19ft',
    brand: 'Jumpflex',
    springType: 'traditional',
    shape: 'square',
    advancedSafety: true,
    meetsAUStandards: false,
    meetsUSStandards: true,
    availableIn: ['AU'],
    priceFrom: 2799,
    sizes: [19],
    displaySize: '19ft square',
    image: '/images/jumpflex/mega-19ft.jpg',
    slug: 'jumpflex-mega-19ft',
    isVuly: false,
    fitsYard: { small: false, medium: false, large: true, longNarrow: false },
    bestFor: 'Huge yards and older jumpers who want maximum square jumping space.',
    metricScores: { bounce: 8, durability: 9, value: 5, warranty: 8 },
    matchReasons: {
      traditional: 'Premium piano-wire spring setup with a giant square footprint',
      shapeRectangle: 'Giant 19ft square — maximum straight-edged jump area for your shape preference',
      safetyEssential: 'High-end safety package built around a heavy-duty square frame',
      safetyNiceToHave: 'Premium safety package for a very large-format trampoline',
      largeYard: '19ft square — only makes sense in a large open yard',
      budget_2500_plus: 'Top-end square trampoline for families wanting maximum jump area',
      bounce: 'Huge square mat gives a broad, powerful jumping zone',
      durability: 'Heavy-duty build and higher weight limits support demanding use',
      warranty: 'Premium Jumpflex frame warranty coverage',
    },
  },

  // ─── Lifespan Kids ─────────────────────────────────────────────────────────

  {
    id: 'lifespan-hyperjump-3-10ft',
    displayName: 'HyperJump 3 Springless 10ft',
    brand: 'Lifespan Kids',
    springType: 'springless',
    shape: 'round',
    advancedSafety: true,
    meetsAUStandards: false,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 429,
    sizes: [10],
    displaySize: '10ft',
    image: '/images/lifespan-kids/hyperjump3-10-ft.webp',
    slug: 'lifespan-hyperjump-3-10ft',
    isVuly: false,
    fitsYard: { small: true, medium: false, large: false, longNarrow: false },
    bestFor: 'Budget-minded families who want a lower-cost springless-style option.',
    metricScores: { bounce: 7, durability: 6, value: 9, warranty: 7 },
    matchReasons: {
      springless: 'Springless strap design removes exposed steel coil springs',
      safetyEssential: 'Safer than basic spring models thanks to the springless setup and enclosed jump area',
      safetyNiceToHave: 'Springless design helps reduce common pinch-point risks',
      smallYard: '10ft footprint suits smaller backyards',
      budget_under_500: 'Low entry price for a springless-style trampoline',
      budget_500_1000: 'Strong value if you want springless on a tighter budget',
      valueForMoney: 'One of the more affordable ways into the springless category',
      warranty: 'Long frame warranty coverage helps offset the budget positioning',
    },
  },

  {
    id: 'lifespan-hyperjump-4-12ft',
    displayName: 'HyperJump 4 Spring 12ft',
    brand: 'Lifespan Kids',
    springType: 'traditional',
    shape: 'round',
    advancedSafety: false,
    meetsAUStandards: false,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 549,
    sizes: [12],
    displaySize: '12ft',
    image: '/images/lifespan-kids/hyperjump4-12-ft.jpg',
    slug: 'lifespan-hyperjump-4-12ft',
    isVuly: false,
    fitsYard: { small: false, medium: true, large: false, longNarrow: false },
    bestFor: 'Families focused on value in a standard 12ft spring trampoline.',
    metricScores: { bounce: 7, durability: 6, value: 8, warranty: 5 },
    matchReasons: {
      traditional: 'Traditional spring layout with a familiar bounce feel',
      mediumYard: '12ft footprint suits medium-sized family backyards',
      budget_500_1000: 'Affordable 12ft spring trampoline in the $500–$1,000 range',
      valueForMoney: 'Solid value for families who want a straightforward backyard trampoline',
    },
  },

  {
    id: 'lifespan-hyperjump-r-8x12',
    displayName: 'HyperJump R Rectangle 8×12',
    brand: 'Lifespan Kids',
    springType: 'traditional',
    shape: 'rectangle',
    advancedSafety: false,
    meetsAUStandards: false,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 899,
    sizes: [12],
    displaySize: '8×12ft rectangle',
    image: '/images/lifespan-kids/hyperjump-r-8x12.jpg',
    slug: 'lifespan-hyperjump-r-8x12',
    isVuly: false,
    fitsYard: { small: false, medium: true, large: true, longNarrow: true },
    bestFor: 'Longer, narrower backyards that suit a rectangle better than a round trampoline.',
    metricScores: { bounce: 8, durability: 6, value: 7, warranty: 5 },
    matchReasons: {
      traditional: 'Rectangle spring layout offers a more directional bounce',
      shapeRectangle: '8×12ft rectangle — the shape you asked for at a mid-range price',
      mediumYard: '8×12ft rectangle fits many medium backyards with better length use',
      largeYard: 'Rectangle footprint opens up more jumping length in a bigger yard',
      longNarrowYard: 'Rectangle format is a natural fit for long, narrow yard shapes',
      budget_500_1000: 'Rectangle trampoline without stepping into the premium price tier',
      bounce: 'Rectangle geometry gives a more controlled, performance-style bounce',
    },
  },

  // ─── Kahuna ───────────────────────────────────────────────────────────────

  {
    id: 'kahuna-classic-12ft',
    displayName: 'Classic 12ft',
    brand: 'Kahuna',
    springType: 'traditional',
    shape: 'round',
    advancedSafety: false,
    meetsAUStandards: false,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 509,
    sizes: [12],
    displaySize: '12ft',
    image: '/images/kahuna/classic-12ft.jpg',
    slug: 'kahuna-classic-12ft',
    isVuly: false,
    fitsYard: { small: false, medium: true, large: false, longNarrow: false },
    bestFor: 'Budget Australian families who just want a simple 12ft backyard trampoline.',
    metricScores: { bounce: 7, durability: 5, value: 9, warranty: 4 },
    matchReasons: {
      traditional: 'Traditional spring setup with a straightforward family bounce',
      mediumYard: '12ft — the classic medium-yard family size',
      budget_500_1000: 'Low-cost 12ft option in the $500–$1,000 range',
      valueForMoney: 'Strong value if your main goal is a cheap family-size trampoline',
    },
  },

  {
    id: 'kahuna-blizzard-10ft',
    displayName: 'Blizzard 10ft',
    brand: 'Kahuna',
    springType: 'traditional',
    shape: 'round',
    advancedSafety: false,
    meetsAUStandards: false,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 509,
    sizes: [10],
    displaySize: '10ft',
    image: '/images/kahuna/blizzard-10ft.jpg',
    slug: 'kahuna-blizzard-10ft',
    isVuly: false,
    fitsYard: { small: true, medium: false, large: false, longNarrow: false },
    bestFor: 'Smaller Australian backyards looking for a cheap 10ft round model.',
    metricScores: { bounce: 7, durability: 5, value: 9, warranty: 4 },
    matchReasons: {
      traditional: 'Traditional spring setup keeps the bounce familiar and simple',
      smallYard: '10ft — a practical size for smaller backyards',
      budget_500_1000: 'Affordable 10ft option without moving into premium pricing',
      valueForMoney: 'Budget-first value for a simple round family trampoline',
    },
  },

  {
    id: 'kahuna-oval-10x15',
    displayName: 'Oval 10×15',
    brand: 'Kahuna',
    springType: 'traditional',
    shape: 'oval',
    advancedSafety: false,
    meetsAUStandards: false,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 899,
    sizes: [15],
    displaySize: '10×15ft oval',
    image: '/images/kahuna/oval-10x15.jpg',
    slug: 'kahuna-oval-10x15',
    isVuly: false,
    fitsYard: { small: false, medium: false, large: true, longNarrow: true },
    bestFor: 'Large or long-narrow yards that need length more than width.',
    metricScores: { bounce: 8, durability: 5, value: 7, warranty: 4 },
    matchReasons: {
      traditional: 'Traditional spring setup in an oval footprint',
      largeYard: '10×15ft oval suits larger yards that have the length to spare',
      longNarrowYard: 'Oval format uses long, narrow yard space better than a large round trampoline',
      budget_500_1000: 'Large-format shape without premium pricing',
      bounce: 'Oval layout gives a longer jumping lane for active kids',
    },
  },

  // ─── OZ Trampolines ────────────────────────────────────────────────────────

  {
    id: 'oz-summit-8ft',
    displayName: 'Summit 8ft',
    brand: 'OZ Trampolines',
    springType: 'traditional',
    shape: 'round',
    advancedSafety: false,
    meetsAUStandards: true,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 299,
    sizes: [8],
    displaySize: '8ft',
    image: '/images/oz-trampolines/summit.jpeg',
    slug: 'oz-summit-8ft',
    isVuly: false,
    fitsYard: { small: true, medium: false, large: false, longNarrow: false },
    bestFor: 'Budget-first Australian families needing a small, AU-standards-compliant option.',
    metricScores: { bounce: 7, durability: 6, value: 10, warranty: 5 },
    matchReasons: {
      traditional: 'Traditional spring setup — familiar bounce',
      meetsStandards: 'Meets Australian AS 4989:2015 standard',
      smallYard: '8ft — one of the smallest options available, perfect for tight spaces',
      budget_under_500: 'Fits comfortably under $500',
      valueForMoney: 'Most affordable way to get an AU-standards-compliant trampoline into a small yard',
    },
  },

  {
    id: 'oz-summit-10ft',
    displayName: 'Summit 10ft',
    brand: 'OZ Trampolines',
    springType: 'traditional',
    shape: 'round',
    advancedSafety: false,
    meetsAUStandards: true,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 399,
    sizes: [10],
    displaySize: '10ft',
    image: '/images/oz-trampolines/summit.jpeg',
    slug: 'oz-summit-10ft',
    isVuly: false,
    fitsYard: { small: true, medium: false, large: false, longNarrow: false },
    bestFor: 'Budget Australian families wanting a larger small-yard option.',
    metricScores: { bounce: 7, durability: 6, value: 10, warranty: 5 },
    matchReasons: {
      traditional: 'Traditional spring setup — familiar bounce',
      meetsStandards: 'Meets Australian AS 4989:2015 standard',
      smallYard: '10ft — fits small to medium yards',
      budget_under_500: 'Under $500 — budget-first option for smaller yards',
      valueForMoney: 'Most affordable 10ft option from an AU-standards-compliant brand',
    },
  },

  {
    id: 'oz-summit-12ft',
    displayName: 'Summit 12ft',
    brand: 'OZ Trampolines',
    springType: 'traditional',
    shape: 'round',
    advancedSafety: false,
    meetsAUStandards: true,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 499,
    sizes: [12],
    displaySize: '12ft',
    image: '/images/oz-trampolines/summit.jpeg',
    slug: 'oz-summit-12ft',
    isVuly: false,
    fitsYard: { small: false, medium: true, large: false, longNarrow: false },
    bestFor: 'Budget Australian families with a medium yard.',
    metricScores: { bounce: 7, durability: 6, value: 10, warranty: 5 },
    matchReasons: {
      traditional: 'Traditional spring setup — familiar bounce',
      meetsStandards: 'Meets Australian AS 4989:2015 standard',
      mediumYard: '12ft — fits medium-sized backyards at the lowest price point',
      budget_under_500: 'Under $500 for a 12ft family trampoline',
      budget_500_1000: 'Well within the $500–$1,000 budget range',
      valueForMoney: 'Most affordable 12ft option that meets AU standards',
    },
  },

  {
    id: 'oz-summit-14ft',
    displayName: 'Summit 14ft',
    brand: 'OZ Trampolines',
    springType: 'traditional',
    shape: 'round',
    advancedSafety: false,
    meetsAUStandards: true,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 599,
    sizes: [14],
    displaySize: '14ft',
    image: '/images/oz-trampolines/summit.jpeg',
    slug: 'oz-summit-14ft',
    isVuly: false,
    fitsYard: { small: false, medium: false, large: true, longNarrow: false },
    bestFor: 'Budget Australian families with a large yard.',
    metricScores: { bounce: 7, durability: 6, value: 10, warranty: 5 },
    matchReasons: {
      traditional: 'Traditional spring setup',
      meetsStandards: 'Meets Australian AS 4989:2015 standard',
      largeYard: '14ft — large size at the lowest price point',
      budget_500_1000: 'Large 14ft trampoline in the $500–$1,000 range',
      valueForMoney: 'Most affordable 14ft option that meets AU standards',
    },
  },

  // ─── GeeTramp ──────────────────────────────────────────────────────────────

  {
    id: 'geetramp-curve',
    displayName: 'Curve',
    brand: 'GeeTramp',
    springType: 'traditional',
    shape: 'round',
    advancedSafety: false,
    meetsAUStandards: true,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 599,
    sizes: [10, 12],
    displaySize: '10ft or 12ft',
    image: '/images/geetramp/curve-12-ft.webp',
    slug: 'geetramp-curve',
    isVuly: false,
    fitsYard: { small: true, medium: true, large: false, longNarrow: false },
    bestFor: 'Value-focused families who want a well-built round with a long warranty.',
    metricScores: { bounce: 8, durability: 8, value: 9, warranty: 8 },
    matchReasons: {
      traditional: 'Traditional coil-spring system with a dependable family bounce',
      shapeRound: 'Classic round shape with an even, centre-guiding bounce',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      smallYard: 'Available in 10ft — fits smaller backyards',
      mediumYard: 'Available in 12ft — ideal for a medium-sized backyard',
      budget_500_1000: 'Starts at $599 — strong build quality in the $500–$1,000 range',
      budget_1000_1500: 'Well under your budget, leaving room for accessories',
      valueForMoney: '10-year frame warranty at a budget-round price',
      durability: 'Heavier-gauge frame than most budget rounds, backed by a 10-year frame warranty',
      warranty: '10-year frame and 3-year mat warranty from GeeTramp',
    },
  },

  {
    id: 'geetramp-force-7x10',
    displayName: 'Force 7×10',
    brand: 'GeeTramp',
    springType: 'traditional',
    shape: 'rectangle',
    advancedSafety: false,
    meetsAUStandards: true,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 1199,
    sizes: [10],
    displaySize: '7×10ft rectangle',
    image: '/images/geetramp/force-7-x-10-ft.webp',
    slug: 'geetramp-force-7x10',
    isVuly: false,
    fitsYard: { small: true, medium: true, large: false, longNarrow: true },
    bestFor: 'Smaller yards that still want a true performance rectangle.',
    metricScores: { bounce: 10, durability: 9, value: 7, warranty: 9 },
    matchReasons: {
      traditional: 'Performance coil springs tuned for a powerful rectangle bounce',
      shapeRectangle: 'True 7×10ft rectangle — the smallest way into a gymnast-style jump lane',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      smallYard: '7×10ft footprint — the rare rectangle that fits a smaller backyard',
      mediumYard: '7×10ft rectangle leaves plenty of clearance in a medium yard',
      longNarrowYard: 'Rectangle format is a natural fit for long, narrow yard shapes',
      budget_1000_1500: 'Entry point to the Force range at $1,199',
      budget_1500_2500: 'Sits below your range — performance rectangle with budget to spare',
      bounce: 'GeeTramp Force is known for one of the best bounces in its class',
      durability: 'Heavy-duty frame with a 10-year warranty',
      warranty: '10-year frame, 3-year mat and 2-year net warranty',
    },
  },

  {
    id: 'geetramp-force-8x12',
    displayName: 'Force 8×12',
    brand: 'GeeTramp',
    springType: 'traditional',
    shape: 'rectangle',
    advancedSafety: false,
    meetsAUStandards: true,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 1499,
    sizes: [12],
    displaySize: '8×12ft rectangle',
    image: '/images/geetramp/force-8-x-12-ft.webp',
    slug: 'geetramp-force-8x12',
    isVuly: false,
    fitsYard: { small: false, medium: true, large: true, longNarrow: true },
    bestFor: 'Families wanting the most popular Force size for all-round performance.',
    metricScores: { bounce: 10, durability: 9, value: 7, warranty: 9 },
    matchReasons: {
      traditional: 'Performance coil springs tuned for a powerful rectangle bounce',
      shapeRectangle: '8×12ft rectangle — a straight, controlled jump lane for training or play',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      mediumYard: '8×12ft rectangle uses a medium yard\'s length efficiently',
      largeYard: 'Leaves room to spare in a large yard while maximising bounce quality',
      longNarrowYard: 'Rectangle format is a natural fit for long, narrow yard shapes',
      budget_1000_1500: 'The most popular Force size at $1,499',
      budget_1500_2500: 'Fits your budget with performance-rectangle credentials',
      bounce: 'GeeTramp Force is known for one of the best bounces in its class',
      durability: 'Heavy-duty frame with a 10-year warranty',
      warranty: '10-year frame, 3-year mat and 2-year net warranty',
    },
  },

  {
    id: 'geetramp-force-9x14',
    displayName: 'Force 9×14',
    brand: 'GeeTramp',
    springType: 'traditional',
    shape: 'rectangle',
    advancedSafety: false,
    meetsAUStandards: true,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 1799,
    sizes: [14],
    displaySize: '9×14ft rectangle',
    image: '/images/geetramp/force-9-x-14-ft.webp',
    slug: 'geetramp-force-9x14',
    isVuly: false,
    fitsYard: { small: false, medium: false, large: true, longNarrow: true },
    bestFor: 'Bigger yards and serious jumpers who want a full-size performance rectangle.',
    metricScores: { bounce: 10, durability: 9, value: 7, warranty: 9 },
    matchReasons: {
      traditional: 'Performance coil springs tuned for a powerful rectangle bounce',
      shapeRectangle: '9×14ft rectangle — a full-length gymnast-style jump lane',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      largeYard: '9×14ft rectangle makes the most of a large backyard',
      longNarrowYard: 'Rectangle format is a natural fit for long, narrow yard shapes',
      budget_1500_2500: 'Full-size performance rectangle at $1,799',
      budget_2500_plus: 'Leaves budget headroom versus premium imported rectangles',
      bounce: 'GeeTramp Force is known for one of the best bounces in its class',
      durability: 'Heavy-duty frame with a 10-year warranty',
      warranty: '10-year frame, 3-year mat and 2-year net warranty',
    },
  },

  {
    id: 'geetramp-force-10x17',
    displayName: 'Force 10×17',
    brand: 'GeeTramp',
    springType: 'traditional',
    shape: 'rectangle',
    advancedSafety: false,
    meetsAUStandards: true,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 2349,
    sizes: [17],
    displaySize: '10×17ft rectangle',
    image: '/images/geetramp/force-10-x-17-ft.webp',
    slug: 'geetramp-force-10x17',
    isVuly: false,
    fitsYard: { small: false, medium: false, large: true, longNarrow: true },
    bestFor: 'Large yards wanting an olympic-length rectangle without the import price tag.',
    metricScores: { bounce: 10, durability: 9, value: 7, warranty: 9 },
    matchReasons: {
      traditional: 'Performance coil springs tuned for a powerful rectangle bounce',
      shapeRectangle: '10×17ft rectangle — near olympic-length jump lane',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      largeYard: '10×17ft needs a big yard but delivers a huge jumping surface',
      longNarrowYard: '17ft of length puts a long, narrow yard to perfect use',
      budget_1500_2500: 'Olympic-length rectangle within your range at $2,349',
      budget_2500_plus: 'Serious jump lane for well under premium import pricing',
      bounce: 'GeeTramp Force is known for one of the best bounces in its class',
      durability: 'Heavy-duty frame with a 10-year warranty',
      warranty: '10-year frame, 3-year mat and 2-year net warranty',
    },
  },

  {
    id: 'geetramp-force-14x16',
    displayName: 'Force 14×16',
    brand: 'GeeTramp',
    springType: 'traditional',
    shape: 'rectangle',
    advancedSafety: false,
    meetsAUStandards: true,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 3199,
    sizes: [16],
    displaySize: '14×16ft rectangle',
    image: '/images/geetramp/force-14-x-16-ft.webp',
    slug: 'geetramp-force-14x16',
    isVuly: false,
    fitsYard: { small: false, medium: false, large: true, longNarrow: false },
    bestFor: 'Huge open yards wanting the biggest jump surface GeeTramp makes.',
    metricScores: { bounce: 10, durability: 9, value: 6, warranty: 9 },
    matchReasons: {
      traditional: 'Performance coil springs tuned for a powerful rectangle bounce',
      shapeRectangle: '14×16ft near-square rectangle — a massive straight-edged jump area',
      meetsStandards: 'Meets Australian AS 4989:2015 safety standard',
      largeYard: '14×16ft is the biggest Force — built for genuinely large yards',
      budget_2500_plus: 'Maximum jump area per dollar in the premium tier',
      bounce: 'GeeTramp Force is known for one of the best bounces in its class',
      durability: 'Heavy-duty frame with a 10-year warranty',
      warranty: '10-year frame, 3-year mat and 2-year net warranty',
    },
  },

  // ─── ACON ──────────────────────────────────────────────────────────────────

  {
    id: 'acon-air-gen2',
    displayName: 'Air GEN2',
    brand: 'ACON',
    springType: 'traditional',
    shape: 'round',
    advancedSafety: false,
    meetsAUStandards: true,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 1599,
    sizes: [12, 14, 15],
    displaySize: '12ft, 14ft or 15ft',
    image: '/images/acon/air-gen2-14-ft.webp',
    slug: 'acon-air-gen2',
    isVuly: false,
    fitsYard: { small: false, medium: true, large: true, longNarrow: false },
    bestFor: 'Families wanting a heavy-duty Finnish round built for year-round outdoor use.',
    metricScores: { bounce: 8, durability: 9, value: 6, warranty: 8 },
    matchReasons: {
      traditional: 'High spring count tuned for a deep, responsive bounce',
      shapeRound: 'Classic round shape with an even, centre-guiding bounce',
      meetsStandards: 'ACON states Australian certification for the 14ft and 15ft sizes',
      mediumYard: 'Available in 12ft — ideal for a medium-sized backyard',
      largeYard: 'Available up to 15ft for your large backyard',
      budget_1500_2500: 'Heavy-duty round in the $1,500–$2,500 range',
      budget_2500_plus: 'Premium build quality with budget left over',
      bounce: 'ACON\'s high spring count delivers one of the best round-trampoline bounces',
      durability: 'Built for harsh Finnish winters — designed to stay outside year-round',
      warranty: '10-year frame and 5-year mat warranty',
    },
  },

  {
    id: 'acon-16-hd-10x17',
    displayName: '16 HD',
    brand: 'ACON',
    springType: 'traditional',
    shape: 'rectangle',
    advancedSafety: false,
    meetsAUStandards: true,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 3599,
    sizes: [17],
    displaySize: '10×17ft rectangle',
    image: '/images/acon/16-hd-10-x-17-ft.webp',
    slug: 'acon-16-hd-10x17',
    isVuly: false,
    fitsYard: { small: false, medium: false, large: true, longNarrow: true },
    bestFor: 'Big families and teens who need a rectangle with a huge weight rating.',
    metricScores: { bounce: 10, durability: 10, value: 5, warranty: 8 },
    matchReasons: {
      traditional: '140 coil springs give a deep, powerful rectangle bounce',
      shapeRectangle: '10×17ft heavy-duty rectangle — a serious straight jump lane',
      meetsStandards: 'ACON states Australian certification for the 16 HD',
      largeYard: '10×17ft footprint suits large open backyards',
      longNarrowYard: '17ft of length puts a long, narrow yard to perfect use',
      budget_2500_plus: 'Premium rectangle engineered for heavy multi-user sessions',
      bounce: 'One of the most powerful bounces of any backyard rectangle',
      durability: '750kg combined weight rating — the strongest build in this quiz',
      warranty: '10-year frame and 5-year mat warranty',
    },
  },

  {
    id: 'acon-x-10x17',
    displayName: 'X',
    brand: 'ACON',
    springType: 'traditional',
    shape: 'rectangle',
    advancedSafety: false,
    meetsAUStandards: false,
    meetsUSStandards: false,
    availableIn: ['AU'],
    priceFrom: 6499,
    sizes: [17],
    displaySize: '10×17ft rectangle',
    image: '/images/acon/x-10-x-17-ft.webp',
    slug: 'acon-x-10x17',
    isVuly: false,
    fitsYard: { small: false, medium: false, large: true, longNarrow: true },
    bestFor: 'Athletes and gymnasts who want ACON\'s flagship performance rectangle.',
    metricScores: { bounce: 10, durability: 10, value: 3, warranty: 8 },
    matchReasons: {
      traditional: '120 performance springs on a flagship rectangle frame',
      shapeRectangle: '10×17ft flagship rectangle — ACON\'s highest-performance jump lane',
      largeYard: '10×17ft footprint needs — and rewards — a large open yard',
      budget_2500_plus: 'Top-of-the-line investment for training-level bounce at home',
      bounce: 'Flagship performance bounce approaching gym-level rebound',
      durability: 'Overbuilt frame designed for daily athletic training',
      warranty: '10-year frame and 5-year mat warranty',
    },
  },
];

type CompareMatcher = {
  brand: string;
  model: string;
  size?: string;
};

const compareMatchers: Record<string, CompareMatcher> = {
  'vuly-thunder-2-pro': { brand: 'Vuly', model: 'Thunder 2 Pro' },
  'vuly-thunder-2': { brand: 'Vuly', model: 'Thunder 2' },
  'vuly-ultra-2-pro': { brand: 'Vuly', model: 'Ultra 2 Pro' },
  'vuly-ultra-2': { brand: 'Vuly', model: 'Ultra 2' },
  'vuly-flare': { brand: 'Vuly', model: 'Flare' },
  'springfree-mini-round': { brand: 'Springfree', model: 'Mini Round Trampoline' },
  'springfree-compact-round': { brand: 'Springfree', model: 'Compact Round Trampoline' },
  'springfree-medium-round': { brand: 'Springfree', model: 'Medium Round Trampoline' },
  'springfree-jumbo-round': { brand: 'Springfree', model: 'Jumbo Round Trampoline' },
  'springfree-compact-oval': { brand: 'Springfree', model: 'Compact Oval Trampoline' },
  'springfree-medium-oval': { brand: 'Springfree', model: 'Medium Oval Trampoline' },
  'springfree-large-oval': { brand: 'Springfree', model: 'Large Oval Trampoline' },
  'springfree-jumbo-oval': { brand: 'Springfree', model: 'Jumbo Oval Trampoline' },
  'springfree-medium-square': { brand: 'Springfree', model: 'Medium Square Trampoline' },
  'springfree-large-square': { brand: 'Springfree', model: 'Large Square Trampoline' },
  'jumpflex-flex-10ft': { brand: 'Jumpflex', model: 'FLEX', size: '10 ft' },
  'jumpflex-flex-12ft': { brand: 'Jumpflex', model: 'FLEX', size: '12 ft' },
  'jumpflex-hero-10ft': { brand: 'Jumpflex', model: 'HERO', size: '10 ft' },
  'jumpflex-hero-12ft': { brand: 'Jumpflex', model: 'HERO', size: '12 ft' },
  'jumpflex-hero-14ft': { brand: 'Jumpflex', model: 'HERO', size: '14 ft' },
  'jumpflex-hero-15ft': { brand: 'Jumpflex', model: 'HERO', size: '15 ft' },
  'jumpflex-mega-14ft': { brand: 'Jumpflex', model: 'MEGA', size: '14 ft' },
  'jumpflex-mega-17ft': { brand: 'Jumpflex', model: 'MEGA', size: '17 ft' },
  'jumpflex-mega-19ft': { brand: 'Jumpflex', model: 'MEGA', size: '19 ft' },
  'lifespan-hyperjump-3-10ft': { brand: 'Lifespan Kids', model: 'HyperJump 3 Springless', size: '10 ft' },
  'lifespan-hyperjump-4-12ft': { brand: 'Lifespan Kids', model: 'HyperJump 4 Spring', size: '12 ft' },
  'lifespan-hyperjump-r-8x12': { brand: 'Lifespan Kids', model: 'HyperJump R Rectangle', size: '8 x 12 ft' },
  'kahuna-classic-12ft': { brand: 'Kahuna', model: 'Classic (Round with Enclosure)', size: '12 ft' },
  'kahuna-blizzard-10ft': { brand: 'Kahuna', model: 'Blizzard (Round)', size: '10 ft' },
  'kahuna-oval-10x15': { brand: 'Kahuna', model: 'Oval', size: '10 x 15 ft' },
  'oz-summit-8ft': { brand: 'Oz Trampolines', model: 'Summit Round', size: '8 ft' },
  'oz-summit-10ft': { brand: 'Oz Trampolines', model: 'Summit Round', size: '10 ft' },
  'oz-summit-12ft': { brand: 'Oz Trampolines', model: 'Summit Round', size: '12 ft' },
  'oz-summit-14ft': { brand: 'Oz Trampolines', model: 'Summit Round', size: '14 ft' },
  'geetramp-curve': { brand: 'GeeTramp', model: 'Curve' },
  'geetramp-force-7x10': { brand: 'GeeTramp', model: 'Force', size: '7 x 10 ft' },
  'geetramp-force-8x12': { brand: 'GeeTramp', model: 'Force', size: '8 x 12 ft' },
  'geetramp-force-9x14': { brand: 'GeeTramp', model: 'Force', size: '9 x 14 ft' },
  'geetramp-force-10x17': { brand: 'GeeTramp', model: 'Force', size: '10 x 17 ft' },
  'geetramp-force-14x16': { brand: 'GeeTramp', model: 'Force', size: '14 x 16 ft' },
  'acon-air-gen2': { brand: 'ACON', model: 'Air GEN2' },
  'acon-16-hd-10x17': { brand: 'ACON', model: '16 HD', size: '10 x 17 ft' },
  'acon-x-10x17': { brand: 'ACON', model: 'X', size: '10 x 17 ft' },
};

function getComparePrice(slug: string): number | null {
  const matcher = compareMatchers[slug];
  if (!matcher) return null;

  const rows = COMPARE_ROWS.filter((row) => {
    if (row.brand !== matcher.brand) return false;
    if (row.model !== matcher.model) return false;
    if (matcher.size && row.size !== matcher.size) return false;
    return row.priceAud !== null;
  });

  if (rows.length === 0) return null;
  return Math.min(...rows.map((row) => row.priceAud as number));
}

export const trampolines: Trampoline[] = baseTrampolines.map((trampoline) => ({
  ...trampoline,
  priceFrom: getComparePrice(trampoline.slug) ?? trampoline.priceFrom,
}));

export function getEligibleTrampolines(country: Country) {
  const resolvedCountry = resolveQuizCountry(country);
  return trampolines.filter((t) => t.availableIn.includes(resolvedCountry));
}
